services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  localstack:
    image: localstack/localstack:latest
    container_name: localstack_aws
    ports:
      - "4566:4566"
      - "4510:4510"
    environment:
      - SERVICES=ec2,iam,s3,dynamodb
      - DEBUG=1
    volumes:
      - localstack_data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

  aws-cli:
    image: amazon/aws-cli:latest
    container_name: aws_cli
    entrypoint: ["/bin/sh", "-c"]
    command: ["tail -f /dev/null"]
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./infra:/scripts

volumes:
  postgres_data:
  rabbitmq_data:
  localstack_data:
