version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: core_banking
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"