spring:
  threads:
    virtual:
      enabled: true
  application:
    name: core-banking-service
  datasource:
    url: jdbc:postgresql://localhost:5432/db_core_banking
    username: postgres
    password: root@123

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
app:
  client:
    authorizer:
      url: "https://run.mocky.io/v3/533cd5d7-63d3-4488-bf8d-4bb8c751c989"

resilience4j:
  circuitbreaker:
    instances:
      authorizer:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
